const SHOW_PANEL_TODO = 'SHOW_PANEL_TODO'
const SHOW_MODAL = 'SHOW_MODAL'
const MODAL_INFO = 'MODAL_INFO'

const SELECT_TODO_ID = 'SELECT_TODO_ID'
const SELECT_LIST_ID = 'SELECT_LIST_ID'

const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'


export { SHOW_PANEL_TODO, SHOW_MODAL, MODAL_INFO,
        SELECT_TODO_ID, SELECT_LIST_ID, SET_ACTIVE_TAB }