const SHOW_PANEL_TODO = 'SHOW_PANEL_TODO'
const SHOW_CHANGE_MODAL = 'SHOW_CHANGE_MODAL'
const SHOW_CONFIRM_MODAL = 'SHOW_CONFIRM_MODAL'
const MODAL_INFO = 'MODAL_INFO'

const SELECT_TODO_ID = 'SELECT_TODO_ID'
const SELECT_LIST_ID = 'SELECT_LIST_ID'

const SET_ACTIVE_TAB = 'SET_ACTIVE_TAB'
const SEARCH_STRING = 'SEARCH_STRING'


export { SHOW_PANEL_TODO, SHOW_CHANGE_MODAL, SHOW_CONFIRM_MODAL, MODAL_INFO,
        SELECT_TODO_ID, SELECT_LIST_ID, SET_ACTIVE_TAB, SEARCH_STRING }