// todo
const TODO_ADD = 'TODO_ADD'
const TODO_COMPLETE = 'TODO_COMPLETE'
const TODO_IMPORTANT = 'TODO_IMPORTANT'
const TODO_DELETE = 'TODO_DELETE'
const CHANGE_TITLE = 'CHANGE_TITLE' 
// list
const ADD_LIST = 'ADD_LIST'
const CHANGE_HEADER = 'CHANGE_HEADER' 
const CHANGE_DATE = 'CHANGE_DATE'
const CHANGE_NOTE = 'CHANGE_NOTE'
const DELETE_LIST = 'DELETE_LIST'

export { 
	TODO_ADD, 
	TODO_COMPLETE, 
	TODO_IMPORTANT, 
	TODO_DELETE,
	ADD_LIST, 
	DELETE_LIST, 
	CHANGE_HEADER, 
	CHANGE_DATE, 
	CHANGE_TITLE, 
	CHANGE_NOTE,
}