const TODO_ADD = 'TODO_ADD'
const TODO_COMPLETE = 'TODO_COMPLETE'
const TODO_IMPORTANT = 'TODO_IMPORTANT'
const TODO_SELECTED = 'TODO_SELECTED'
const TODO_DELETE = 'TODO_DELETE'

const CHANGE_HEADER = 'CHANGE_HEADER' // list
const CHANGE_TITLE = 'CHANGE_TITLE' // todo
const CHANGE_DATE = 'CHANGE_DATE'
const CHANGE_NOTE = 'CHANGE_NOTE'




export { TODO_ADD, TODO_COMPLETE, TODO_IMPORTANT, TODO_SELECTED, TODO_DELETE,
        CHANGE_HEADER, CHANGE_DATE, CHANGE_TITLE, CHANGE_NOTE
        }